#!/bin/bash
# Installation script for cc-fi with multiple installation methods

set -e

echo "=== cc-fi Installation ==="
echo

# Check for Python 3.12+
if ! command -v python3 &> /dev/null; then
    echo "Error: Python 3 not found. Please install Python 3.12 or higher."
    exit 1
fi

# Check for required tools
echo "Checking dependencies..."

# Check for fzf (required for interactive mode)
if ! command -v fzf &> /dev/null; then
    echo "Warning: fzf not found. Required for interactive mode."
    echo "  macOS: brew install fzf"
    echo "  Linux: apt install fzf"
    echo
fi

# Check for fd (required for directory browser)
if ! command -v fd &> /dev/null; then
    echo "Warning: fd not found. Required for directory browser feature."
    echo "  macOS: brew install fd"
    echo "  Linux: apt install fd-find"
    echo
fi

echo

# Offer installation methods based on available tools
echo "Select installation method:"
echo

INSTALL_METHOD=""

# Check for pipx
if command -v pipx &> /dev/null; then
    echo "  1) pipx (Recommended - isolated install, works from anywhere)"
    INSTALL_METHOD="pipx"
fi

# Check for uv
if command -v uv &> /dev/null; then
    if [ -z "$INSTALL_METHOD" ]; then
        echo "  1) uv tool (Modern - isolated install, works from anywhere)"
    else
        echo "  2) uv tool (Modern - isolated install, works from anywhere)"
    fi
    if [ -z "$INSTALL_METHOD" ]; then
        INSTALL_METHOD="uv"
    fi
fi

# Always offer manual option
if [ -n "$INSTALL_METHOD" ]; then
    echo "  3) Manual (Creates wrapper script at ~/.local/bin/cc-fi)"
else
    echo "  1) Manual (Creates wrapper script at ~/.local/bin/cc-fi)"
fi

echo

read -p "Enter choice (default: 1): " choice
choice=${choice:-1}

case "$choice" in
    1)
        if [ "$INSTALL_METHOD" = "pipx" ]; then
            echo
            echo "Installing with pipx..."
            pipx install .
            echo
            echo "✓ Installation complete!"
            echo
            echo "Run from anywhere: cc-fi"
            echo
            exit 0
        elif [ "$INSTALL_METHOD" = "uv" ]; then
            echo
            echo "Installing with uv tool..."
            uv tool install .
            echo
            echo "✓ Installation complete!"
            echo
            echo "Run from anywhere: cc-fi"
            echo "Note: Make sure ~/.local/bin is in your PATH"
            echo
            exit 0
        fi
        # Fall through to manual install
        ;;
    2)
        if [ "$INSTALL_METHOD" = "pipx" ] && command -v uv &> /dev/null; then
            echo
            echo "Installing with uv tool..."
            uv tool install .
            echo
            echo "✓ Installation complete!"
            echo
            echo "Run from anywhere: cc-fi"
            echo "Note: Make sure ~/.local/bin is in your PATH"
            echo
            exit 0
        fi
        # Fall through to manual install
        ;;
    3|*)
        # Manual install
        ;;
esac

# Manual installation with wrapper script
echo
echo "Installing manually with virtual environment..."
echo

# Check for uv, install if needed
if ! command -v uv &> /dev/null; then
    echo "Installing uv..."
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.local/bin:$PATH"
fi

# Create virtual environment
echo "Creating virtual environment..."
uv venv

# Install package
echo "Installing cc-fi..."
source .venv/bin/activate
uv pip install -e .

# Run tests
echo "Running tests..."
if command -v pytest &> /dev/null; then
    pytest tests/unit/ -q
else
    uv pip install pytest pytest-mock
    pytest tests/unit/ -q
fi

# Create wrapper script
WRAPPER_DIR="$HOME/.local/bin"
INSTALL_DIR="$PWD"

echo
echo "Creating wrapper script..."
mkdir -p "$WRAPPER_DIR"

cat > "$WRAPPER_DIR/cc-fi" << EOF
#!/bin/bash
# CC-FI wrapper script - auto-generated by install.sh
# Source: $INSTALL_DIR
exec "$INSTALL_DIR/.venv/bin/python" -m cc_fi.main "\$@"
EOF

chmod +x "$WRAPPER_DIR/cc-fi"

echo "✓ Installation complete!"
echo
echo "Wrapper script created at: $WRAPPER_DIR/cc-fi"
echo

# Check if ~/.local/bin is in PATH
if [[ ":$PATH:" == *":$HOME/.local/bin:"* ]]; then
    echo "✓ ~/.local/bin is already in your PATH"
    echo
    echo "Run from anywhere: cc-fi"
else
    echo "⚠ ~/.local/bin is NOT in your PATH"
    echo
    echo "To use cc-fi from anywhere, add this to your shell profile:"
    echo

    # Detect shell
    if [ -n "$ZSH_VERSION" ]; then
        SHELL_RC="~/.zshrc"
    elif [ -n "$BASH_VERSION" ]; then
        SHELL_RC="~/.bashrc"
    else
        SHELL_RC="~/.profile"
    fi

    echo "  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> $SHELL_RC"
    echo "  source $SHELL_RC"
    echo
    echo "Or run directly: $WRAPPER_DIR/cc-fi"
fi

echo
echo "To uninstall:"
echo "  rm $WRAPPER_DIR/cc-fi"
echo "  rm -rf $INSTALL_DIR/.venv"
echo
